# install.packages("ggrepel")
# install.packages("gganimate")
library(gifski)
library(ggrepel)
library(gganimate)
library(glue)
library(dplyr)

library(tidyverse)
library(glitr)
library(gophr)
#  install.packages("remotes")
# remotes::install_github("USAID-OHA-SI/glamr", build_vignettes = TRUE)
library(glamr)
# ls(package:glamr)
# install.packages("usethis")
library(usethis)
# set_email("jstephens@usaid.gov")
load_secrets(service = c("email"))