
library(tidyverse)
library(dplyr)
library(glitr)
library(gophr)
#  install.packages("remotes")
# remotes::install_github("USAID-OHA-SI/glamr", build_vignettes = TRUE)
library(glamr)
# ls(package:glamr)
#  install.packages("usethis")
library(usethis)
install.packages("keyring")
 set_email("jstephens@usaid.gov")
load_secrets(service = c("email"))


# install.packages("ggrepel")
# install.packages("gganimate")
# install.packages("gifski")
library(glue)
library(gifski)
library(ggrepel)
library(gganimate)
